### ISSUE TITLE
UGS cannot control the spindle

### ISSUE THREAD

**Issue by chengeV587** [winder/Universal-G-Code-Sender#2503]
**log file:** [messages.log](https://github.com/winder/Universal-G-Code-Sender/files/14859696/messages.log)
### Version

2.1.6

### Hardware / Firmware

FluidNC

### What happened

Sending M3 S5000, M5 commands through the console and switching the Spindle button of the overrides panel failed to control the spindle，an attempt has been made to switch to tool number 0 by T0。Jog control works fine。
I've tried other Gcode senders like Openbuilds, CNCjs, and they all work fine, but UGS is my favorite。
![image](https://github.com/winder/Universal-G-Code-Sender/assets/102453523/190803ad-9dc9-4982-a0e8-fc14fec83b9f)

### How to reproduce
Every time

### Operating System

Window Version: Windows 11
FluidNC Version: 3.7.16（3.7.13， 3.7.4 also tested）
UGS Version: Universal Gcode Sender 20240308, V2.1.6

### Anything else
FluidNC and UGS connection mode: Tried Serial and TCP results are the same。
![image](https://github.com/winder/Universal-G-Code-Sender/assets/102453523/fd012417-e324-43f7-876f-acf756f13d57)

When I connect to UGS and query the state of the machine with the $$instruction, I get this result：
![image](https://github.com/winder/Universal-G-Code-Sender/assets/102453523/6f85f5c3-bc04-403c-8fbe-2e2f7ea91442)
Where $30=255 is incorrect and $30=12000 is correct。
After connecting UGS, other Gcode Sender such as CNCjs will get the same result of $$ instruction query, and the spindle can not be controlled. The machine must be restarted.
The result of the $$ query sent by CNCjs is as follows:
![image](https://github.com/winder/Universal-G-Code-Sender/assets/102453523/4fb24536-43ae-43eb-9a08-959f119d1800)

**FluidNC configuration file:**
name: My3020Config
board: None
start:
  must_home: false
  deactivate_parking: false
stepping:
  engine: I2S_STATIC
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
axes:
  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 300
    motor0:
      limit_all_pin: gpio.36:low
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.6
        direction_pin: i2so.7
        disable_pin: NO_PIN
    soft_limits: false
  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 200
    soft_limits: false
    motor0:
      limit_all_pin: gpio.39:low
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.4
        direction_pin: i2so.5
        disable_pin: NO_PIN
  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 20
    max_travel_mm: 60
    soft_limits: false
    motor0:
      limit_all_pin: gpio.34:low
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.2
        direction_pin: i2so.3
        disable_pin: NO_PIN
  a:
    steps_per_mm: 35.556
    max_rate_mm_per_min: 144000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 360
    soft_limits: false
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.35:low
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.15
        direction_pin: i2so.1
        disable_pin: NO_PIN
  shared_stepper_disable_pin: i2so.0
  shared_stepper_reset_pin: NO_PIN
control:
  safety_door_pin: gpio.14:pu:low
  feed_hold_pin: gpio.26:pu:low
  cycle_start_pin: gpio.25:pu:low
  reset_pin: gpio.32:pu:low
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: gpio.33:pu:low
macros:
  macro0: $SD/Run=00.nc
coolant:
  flood_pin: i2so.11
  mist_pin: NO_PIN
  delay_ms: 0
probe:
  pin: gpio.27:pu:low
  check_mode_start: true
Laser:
  output_pin: gpio.2
  enable_pin: NO_PIN
  tool_num: 2
spi:
  miso_pin: gpio.19:pu
  mosi_pin: gpio.23:pu
  sck_pin: gpio.18
sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5:pu
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
10V:
  forward_pin: i2so.9
  reverse_pin: i2so.10
  output_pin: gpio.15:pu
  enable_pin: gpio.4:pu
  direction_pin: NO_PIN
  tool_num: 0
  speed_map: 0=0.000% 1200=10.000% 6000=50.000% 12000=100.000%
  off_on_alarm: true
status_outputs:
  report_interval_ms: 500
  idle_pin: NO_PIN
  run_pin: i2so.12
  hold_pin: i2so.13
  alarm_pin: i2so.14
i2c0:
  sda_pin: gpio.16
  scl_pin: gpio.13
oled:
  i2c_num: 0
  i2c_address: 60
  width: 128
  height: 64
  radio_delay_ms: 0

**Comment by breiler** [comment]
This worked just fine for me, recheck your settings

My version
```
> $I
[VER:3.7 FluidNC v3.7.16:]
[OPT:PHS]
[MSG:Machine: New configuration]
ok
```

My settings
```
> $$
$22=1
$21=0
$20=0
$102=800.000
$101=800.000
$100=800.000
$112=1200.000
$111=1200.000
$110=1200.000
$122=15.000
$121=15.000
$120=15.000
$132=1000.000
$131=1000.000
$130=1000.000
$10=1
$30=12000
ok
```

Spindle control works, however the M5 command for stopping the spindle will still make the status report a spindle speed. I will post a bug report to the FluidNC team.
```
> m3 S12000
ok
> ?
<Idle|MPos:0.000,0.000,0.000|FS:0,12000|Pn:Y>
ok
> m5
ok
> ?
<Idle|MPos:0.000,0.000,0.000|FS:0,12000|Pn:Y>
ok
> m3 S0
ok
> ?
<Idle|MPos:0.000,0.000,0.000|FS:0,0|Pn:Y>
ok
```

My config file
```yaml
> $config/dump
board: None
name: New configuration
meta: 
stepping: 
  engine: RMT
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
  segments: 12

spi: 
  miso_pin: NO_PIN
  mosi_pin: NO_PIN
  sck_pin: NO_PIN

sdcard: 
  cs_pin: NO_PIN
  card_detect_pin: NO_PIN
  frequency_hz: 8000000

kinematics: 
  Cartesian: 

axes: 
  shared_stepper_disable_pin: gpio.13
  shared_stepper_reset_pin: NO_PIN
  x: 
    steps_per_mm: 800.000000
    max_rate_mm_per_min: 1200.000000
    acceleration_mm_per_sec2: 15.000000
    max_travel_mm: 1000.000000
    soft_limits: false
    homing: 
      cycle: 2
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000000
      feed_mm_per_min: 50.000000
      seek_mm_per_min: 200.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.17:low:pu
      hard_limits: false
      pulloff_mm: 2.000000
      standard_stepper: 
        step_pin: gpio.12
        direction_pin: gpio.14:low
        disable_pin: NO_PIN

  y: 
    steps_per_mm: 800.000000
    max_rate_mm_per_min: 1200.000000
    acceleration_mm_per_sec2: 15.000000
    max_travel_mm: 1000.000000
    soft_limits: false
    homing: 
      cycle: 2
      allow_single_axis: true
      positive_direction: false
      mpos_mm: 0.000000
      feed_mm_per_min: 50.000000
      seek_mm_per_min: 200.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.4:low:pu
      hard_limits: false
      pulloff_mm: 2.000000
      standard_stepper: 
        step_pin: gpio.26
        direction_pin: gpio.15
        disable_pin: NO_PIN

  z: 
    steps_per_mm: 800.000000
    max_rate_mm_per_min: 1200.000000
    acceleration_mm_per_sec2: 15.000000
    max_travel_mm: 1000.000000
    soft_limits: false
    homing: 
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000000
      feed_mm_per_min: 50.000000
      seek_mm_per_min: 200.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.16:low:pu
      hard_limits: false
      pulloff_mm: 1.000000
      standard_stepper: 
        step_pin: gpio.27
        direction_pin: gpio.33:low
        disable_pin: NO_PIN

control: 
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN

coolant: 
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe: 
  pin: gpio.32:low:pu
  toolsetter_pin: NO_PIN
  check_mode_start: false

macros: 
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 
  after_homing: 
  after_reset: 
  after_unlock: 

start: 
  must_home: true
  deactivate_parking: false
  check_limits: false

parking: 
  enable: false
  axis: Z
  target_mpos_mm: -5.000000
  rate_mm_per_min: 800.000000
  pullout_distance_mm: 5.000000
  pullout_rate_mm_per_min: 250.000000

user_outputs: 
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN

PWM: 
  pwm_hz: 5000
  direction_pin: NO_PIN
  output_pin: gpio.2
  enable_pin: gpio.22
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 100
  speed_map: 0=0.00% 12000=100.00%
  off_on_alarm: false

arc_tolerance_mm: 0.002000
junction_deviation_mm: 0.010000
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
ok
```
